[package]
name = "bef93"
version = "0.1.0"
authors = ["Arnav Borborah <arnavborborah11@gmail.com>"]

[dependencies]
rand = "0.6.1"

[dependencies.clap]
version = "2.32.0"
default-features = false
features = ["suggestions"]
