[package]
name = "bef93"
version = "1.0.0"
authors = ["Arnav Borborah <arnavborborah11@gmail.com>"]

[dependencies]
rand = "0.7.3"

[dependencies.clap]
version = "3.0.0"
default-features = false
features = ["suggestions"]

[dev-dependencies]
assert_cmd = "1.0.1"
