[package]
name = "bef93"
version = "1.0.0"
authors = ["Arnav Borborah <arnavborborah11@gmail.com>"]

[dependencies]
rand = "0.6.5"

[dependencies.clap]
version = "2.33.0"
default-features = false
features = ["suggestions"]

[dev-dependencies]
assert_cmd = "0.11.1"
